services:
  - type: web
    name: whatsapp-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: REQ_API
        value: "API-KEY"
